/**
 * PDF Export Utilities
 * Generate formatted PDF documents from debates
 */

import type { Message } from '@/lib/stores/debate-store';
import { PERSONAS } from '@/lib/agents/personas';

interface ExportOptions {
  title: string;
  question: string;
  messages: Message[];
  timestamp: number;
  model: string;
  mode: string;
  advisors: string[];
}

/**
 * Export debate as PDF using browser's print functionality
 * This is a lightweight approach that works without external libraries
 */
export function exportToPDF(options: ExportOptions): void {
  const { title, question, messages, timestamp, model, mode, advisors } = options;

  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Pop-up blocked. Please allow pop-ups for PDF export.');
  }

  // Generate HTML content
  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title>${title}</title>
        <style>
          @media print {
            @page { margin: 1in; }
            body { margin: 0; }
          }

          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            line-height: 1.6;
            color: #1a1a1a;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
          }

          h1 {
            color: #0066cc;
            border-bottom: 3px solid #0066cc;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }

          h2 {
            color: #333;
            margin-top: 30px;
            margin-bottom: 15px;
          }

          h3 {
            color: #666;
            margin-top: 20px;
            margin-bottom: 10px;
          }

          .metadata {
            background: #f5f5f5;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 30px;
            font-size: 14px;
            color: #666;
          }

          .metadata-item {
            margin: 5px 0;
          }

          .question {
            background: #e3f2fd;
            padding: 20px;
            border-left: 4px solid #2196f3;
            margin-bottom: 30px;
            border-radius: 4px;
          }

          .advisor-response {
            margin: 20px 0;
            padding: 15px;
            border-left: 4px solid #ddd;
            background: #fafafa;
            page-break-inside: avoid;
          }

          .advisor-name {
            font-weight: bold;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            gap: 8px;
          }

          .round-header {
            margin: 30px 0 20px 0;
            padding: 10px;
            background: #f0f0f0;
            border-radius: 4px;
            font-weight: bold;
          }

          .consensus {
            background: #e8f5e9;
            padding: 20px;
            border-left: 4px solid #4caf50;
            margin-top: 30px;
            border-radius: 4px;
            page-break-inside: avoid;
          }

          .sources {
            background: #fff3e0;
            padding: 15px;
            margin-top: 15px;
            border-radius: 4px;
            font-size: 12px;
          }

          .source-item {
            margin: 8px 0;
            padding-left: 15px;
          }

          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #999;
            text-align: center;
          }

          @media print {
            .no-print { display: none; }
            body { font-size: 11pt; }
            h1 { font-size: 18pt; }
            h2 { font-size: 14pt; }
            h3 { font-size: 12pt; }
          }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(title)}</h1>

        <div class="metadata">
          <div class="metadata-item"><strong>Date:</strong> ${new Date(timestamp).toLocaleString()}</div>
          <div class="metadata-item"><strong>Model:</strong> ${model}</div>
          <div class="metadata-item"><strong>Mode:</strong> ${mode}</div>
          <div class="metadata-item"><strong>Advisors:</strong> ${advisors.map(a => {
            const persona = PERSONAS[a as keyof typeof PERSONAS];
            return persona?.name || a;
          }).join(', ')}</div>
        </div>

        <h2>Question</h2>
        <div class="question">
          ${escapeHtml(question)}
        </div>

        <h2>Debate</h2>
        ${generateDebateHTML(messages)}

        <div class="footer">
          Generated by SelfStarterSuite - AI Council Platform<br>
          https://github.com/Grandillionaire/SelfStarterSuite
        </div>

        <div class="no-print" style="position: fixed; top: 20px; right: 20px;">
          <button onclick="window.print()" style="padding: 10px 20px; background: #0066cc; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 14px;">
            Print / Save as PDF
          </button>
          <button onclick="window.close()" style="padding: 10px 20px; background: #666; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 14px; margin-left: 10px;">
            Cancel
          </button>
        </div>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();

  // Auto-trigger print dialog after content loads
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };
}

function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

function generateDebateHTML(messages: Message[]): string {
  let html = '';
  let currentRound = 0;

  messages.forEach((message) => {
    if (message.type === 'moderator' && message.content.includes('Round')) {
      currentRound++;
      html += `<div class="round-header">📍 ${escapeHtml(message.content)}</div>`;
    } else if (message.type === 'agent' && message.agent) {
      const persona = PERSONAS[message.agent as keyof typeof PERSONAS];
      html += `
        <div class="advisor-response">
          <div class="advisor-name">
            <span>${persona?.avatar || '🤖'}</span>
            <span style="color: ${persona?.color || '#666'}">${persona?.name || message.agent}</span>
          </div>
          <div>${escapeHtml(message.content).replace(/\n/g, '<br>')}</div>
          ${message.sources && message.sources.length > 0 ? `
            <div class="sources">
              <strong>Sources:</strong>
              ${message.sources.map((s, i) => `
                <div class="source-item">
                  [${i + 1}] ${escapeHtml(s.title)}<br>
                  <a href="${s.url}" target="_blank">${s.url}</a>
                </div>
              `).join('')}
            </div>
          ` : ''}
        </div>
      `;
    } else if (message.type === 'final') {
      html += `
        <div class="consensus">
          <h3>✅ Council Consensus</h3>
          <div>${escapeHtml(message.content).replace(/\n\n/g, '</p><p>').replace(/\n/g, '<br>')}</div>
        </div>
      `;
    }
  });

  return html;
}

/**
 * Quick export with default settings
 */
export function quickExportToPDF(title: string, messages: Message[]): void {
  const userMessages = messages.filter(m => m.type === 'user');
  const question = userMessages[0]?.content || 'No question';

  exportToPDF({
    title,
    question,
    messages,
    timestamp: Date.now(),
    model: 'Claude Sonnet 4.5',
    mode: 'Standard',
    advisors: ['naval', 'elon', 'larry', 'alex', 'pavel'],
  });
}
